spring:
  application:
    name: freight-nexus
  datasource:
    url: jdbc:postgresql://localhost:5433/freightdb?TimeZone=UTC
    username: freight
    password: freight123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

server:
  port: 8080

app:
  jwt:
    secret: ZnJlaWdodC1uZXh1cy1qd3Qtc2VjcmV0LWtleS1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQtb25seQ==
    expiry-hours: 24
