name: Bug report
description: Something isn't working as expected
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: "Java version, OS, Docker version"
